### ISSUE TITLE
Support arbitrary `@`-blocks

### ISSUE THREAD

**Issue by necolas** [reworkcss/css#16]
There's also `@viewport` (and `-ms`, `-webkit`, `-o` prefixed versions) and probably some others that I've forgotten or don't know about. People building preprocessors might also want to use custom @-rules.

(Moved from https://github.com/reworkcss/css-stringify/issues/9)

**Comment by mtlehtin** [comment]
+1

+1

We have the same issue when parsin third party css (AlloyUI)
```
@-ms-viewport {
  .wrapper {
    width: device-width; } }

@-ms-keyframes progress-bar-stripes {
  .aui from {
    background-position: 40px 0; }
  .aui to {
    background-position: 0 0; } }
```

Is causing error: missing '}'
