### ISSUE TITLE
support for running in the browser

### ISSUE THREAD

**Issue by charlierudolph** [reworkcss/css#68]
I'm currently using this in the browser with webpack. However when compiling the assets I get the warning that the the module `fs` cannot be found. Used in `lib/stringify/source-map-support.js`. This is an irrelevant error for me as I'm not using the source maps. 

It would be great if there was a browser compatible version available that simply left out the source map support.

**Comment by ai** [comment]
In [PostCSS](https://github.com/postcss/postcss/) I made browser build by Browserify and then use [this check](https://github.com/postcss/postcss/blob/master/lib/previous-map.js#L80).

**Comment by kumarharsh** [comment]
@ai the "this check" link is broken. Can you fix the link by using the canonical url?

**Comment by ai** [comment]
@kumarharsh https://github.com/postcss/postcss/blob/master/lib/previous-map.es6#L85

**Comment by lydell** [comment]
Github pro tip: Press `y` to change the URL to the latest commit, so the link works in the future as well. For @ai’s link above: https://github.com/postcss/postcss/blob/0accf88f55c8b08b478f2a3439d157b116d69774/lib/previous-map.es6#L85

**Comment by charlierudolph** [comment]
I'm no longer in need of this.
