### ISSUE TITLE
Clicking on the plus/minus doesn't expand the node

### ISSUE THREAD

**Issue by tkreis** [reworkcss/css#82]
![image](https://cloud.githubusercontent.com/assets/2585243/11480319/7eab26ca-975c-11e5-874d-27adc744cc56.png)

**Comment by conradz** [comment]
I believe you are referring to http://iamdustan.com/reworkcss_ast_explorer/. Issues with that tool should be raised at https://github.com/iamdustan/reworkcss_ast_explorer.

**Comment by tkreis** [comment]
Yep, pasted it into the wrong tab. Sorry for the troubles
